### ISSUE TITLE
Example is out of date

### ISSUE THREAD

**Issue by cornfeedhobo** [Apparence-io/camera_awesome#139] opened 2022-08-09 03:27 UTC
## Steps to Reproduce

Run the example files in debug and watch the log

## Expected results

- not using google.bintray.com
- no stack traces

## Actual results

- using google.bintray.com
- lots of stack traces

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| motorola | moto g  | 9 |

</details>

**Comment by g-apparence** [comment] 2022-08-12 19:49
duplicate of #138

**Closed by g-apparence** 2022-08-12 19:49 UTC
