### ISSUE TITLE
Exception MUST_CALL_INIT when opening Camera Awesome widget

### ISSUE THREAD

**Issue by jarren-meep** [Apparence-io/camera_awesome#61] opened 2020-12-21 01:44 UTC
Hello, I'm on Android 9, Blackview 6100 (BV610) and the bug still persists, however only PlatformException (PlatformException(MUST_CALL_INIT, , , null)) will appear, the texture error doesn't appear.

Not sure if it's the same error as UlanNurmatov, but I'll post it here anyway because this seems similar enough

```Dart
import 'dart:io';
import 'dart:typed_data';

import 'package:camerawesome/camerapreview.dart';
import 'package:camerawesome/camerawesome_plugin.dart';
import 'package:camerawesome/models/capture_modes.dart';
import 'package:camerawesome/models/flashmodes.dart';
import 'package:camerawesome/models/orientations.dart';
import 'package:camerawesome/models/sensors.dart';
import 'package:camerawesome/picture_controller.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:image/image.dart' as image;

class FRCameraScreen extends StatefulWidget {
  @override
  _FRCameraScreenState createState() => _FRCameraScreenState();
}

class _FRCameraScreenState extends State<FRCameraScreen> {
  String _lastPhotoPath;
  ValueNotifier<CameraFlashes> _switchFlash = ValueNotifier(CameraFlashes.NONE);
  ValueNotifier<Sensors> _sensor = ValueNotifier(Sensors.BACK);
  ValueNotifier<CaptureModes> _captureMode = ValueNotifier(CaptureModes.PHOTO);
  ValueNotifier<Size> _photoSize = ValueNotifier(null);
  ValueNotifier<bool> _enableAudio = ValueNotifier(true);
  String imgName;
  int number = 0;

  Stream<Uint8List> previewStream;

  PictureController _pictureController = new PictureController();

  _takePhoto() async {
    final Directory extDir = await getExternalStorageDirectory();
    final testDir =
        await Directory('${extDir.path}/test').create(recursive: true);
    final String filePath = imgName != null
        ? '${testDir.path}/${DateTime.now().millisecondsSinceEpoch}.jpg'
        : '${testDir.path}/photo_test.jpg';
    await _pictureController.takePicture(filePath);
    // lets just make our phone vibrate
    HapticFeedback.mediumImpact();
    _lastPhotoPath = filePath;
    setState(() {});

    print("----------------------------------");
    print("TAKE PHOTO CALLED");
    final file = File(filePath);
    print("==> hastakePhoto : ${file.exists()} | path : $filePath");
    final img = image.decodeImage(file.readAsBytesSync());
    print("==> img.width : ${img.width} | img.height : ${img.height}");
    print("----------------------------------");

    setState(() {});
  }

  _onPermissionsResult(bool granted) {
    if (!granted) {
      print("Not Granted");
    } else {
      print("Granted");
    }
  }

  Widget _buildPreviewStream() {
    if (previewStream == null) return Container();
    return Positioned(
      left: 32,
      bottom: 120,
      child: StreamBuilder(
        stream: previewStream,
        builder: (context, snapshot) {
          if (!snapshot.hasData && snapshot.data.isNotEmpty) return Container();
          List<Uint8List> data = snapshot.data;
          print(
              "...${DateTime.now()} new image received... ${data.last.lengthInBytes} bytes");
          return Image.memory(
            data.last,
            width: 120,
          );
        },
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    return CameraAwesome(
      testMode: true,
      onPermissionsResult: _onPermissionsResult,
      selectDefaultSize: (List<Size> availableSizes) => Size(640, 480),
      onCameraStarted: () {},
      onOrientationChanged: (CameraOrientations newOrientation) {},
      sensor: _sensor,
      switchFlashMode: _switchFlash,
      captureMode: _captureMode,
      orientation: DeviceOrientation.portraitUp,
      fitted: true,
      enableAudio: _enableAudio,
      photoSize: _photoSize,
    );
  }
}
```
No error seems to show in my console, the error only appears and once I press Continue, the camera is working and I can move on.
Also, this error only happens when I fully stop the app, the error doesn't appear anymore when I hot restart, if that's any useful information.

Hope this helps! (somehow)

edited: to format use this syntax ```dart

## About your device

| Brand   | Model       | OS        |
| ------- | ----------- | --------- |
| *BlackView* | *BV6100*  | *Android 9*  |

</details>

**Comment by g-apparence** [comment] 2021-01-04 09:19
Duplicate of #60

**Comment by g-apparence** [comment] 2021-01-04 16:18
Hi, 
here is the method that makes this
```java
private void _handleGetTextures(MethodCall call, Result result) {
    if(mCameraPreview == null) {
      result.error("MUST_CALL_INIT", "", "");
      return;
    }
    try {
        long id = mCameraPreview.getFlutterTexture();
        result.success(id);
    } catch (RuntimeException e) {
        result.error("TEXTURE_NOT_FOUND", "cannot find texture", "");
    }
}
```
The error is just that initialization takes much time. So to reproduce it I simply made the init method much slower.
Flutter start showing our widget before initialization ends, so Flutter FutureBuilder gets an error and shows you a red screen. 
As it's only from platform it's not in your console. In release mode Flutter won't show any red screen from futureBuilder. 

I can remove this error but I would prefer keeping it. In release mode this error should not be seen. 
To prevent you and stop fearing it, I'll prevent the build from our widget if we are not fully initialized.

**Closed** 2021-01-04 16:57 UTC
Labels: android

**Comment by Technorocker** [comment] 2022-03-02 22:01
How are you not getting an error for this line

`ValueNotifier<Size> _photoSize = ValueNotifier(null);`

Im getting "The argument type'Null' can't be assigned tot he parameter type 'Size' yet its in the example code and little code section on the readme page. "
